FROM nginx:latest

EXPOSE 80

COPY ./manifest.json /usr/share/nginx/html
COPY ./pwabuilder-sw.js /usr/share/nginx/html
COPY index.html /usr/share/nginx/html
COPY CHANGELOG.md /usr/share/nginx/html
COPY LICENSE /usr/share/nginx/html
COPY www /usr/share/nginx/html/www
COPY archives/README.md /usr/share/nginx/html/archives/README.md