# Created using wingetcreate

PackageIdentifier: Kiwix.KiwixJS
PackageVersion: 1.6.0.0
Installers:
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.10240.0
  Architecture: neutral
  InstallerType: msix
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.6.0/KiwixWebApp_1.6.0.0_AnyCPU.appxbundle
  InstallerSha256: 22108A829F112AB65A31EADCBBB8E0832128653F4BB691CEBB9CDF64134644D8
  SignatureSha256: CC655D9F014D0427BF3C43C995701273B63C91095514497E61D706F9B2AC999B
  PackageFamilyName: Kiwix.KiwixJS_qwjmsdmcnwx12
ManifestType: installer
ManifestVersion: 1.0.0
