FROM nginx:latest

EXPOSE 80

COPY ./dist/manifest.json /usr/share/nginx/html
COPY ./dist/service-worker.js /usr/share/nginx/html
COPY ./dist/index.html /usr/share/nginx/html
COPY ./dist/CHANGELOG.md /usr/share/nginx/html
COPY ./dist/LICENSE /usr/share/nginx/html
COPY ./dist/www /usr/share/nginx/html/www
COPY ./dist/archives/README.md /usr/share/nginx/html/archives/README.md
# COPY ./docker/secure_origin.conf /etc/nginx/conf.d/secure_origin.conf