# Created using wingetcreate

PackageIdentifier: Kiwix.WikiMed
PackageVersion: 1.6.2.0
Installers:
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.10240.0
  Architecture: neutral
  InstallerType: msix
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.6.2-WikiMed/KiwixWebAppWikiMed_1.6.2.0_AnyCPU.appxbundle
  InstallerSha256: F06DCC0340124DDEBF6532FFC1C5CEC9EC5AE9696E457228DCB166CBCF6B1CDD
  SignatureSha256: E0BB72C4EA259C621EC4666EA431BA2390C67A535C95F0B1EDE4CA97BC79BAC1
  PackageFamilyName: Kiwix.WikiMed_qwjmsdmcnwx12
ManifestType: installer
ManifestVersion: 1.0.0
