# Created using wingetcreate

PackageIdentifier: Kiwix.KiwixJS.Electron
PackageVersion: 1.7.2-E
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.7.2E/Kiwix.JS.PWA.Setup.1.7.2-E.exe
  InstallerSha256: 0328BDC2F2F04CDE70EBAEEF67F6DD402DAFA60F335E52BC2C8DDD8B155AC016
  InstallerSwitches:
    Custom: /CURRENTUSER
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.7.2E/Kiwix.JS.PWA.Setup.1.7.2-E.exe
  InstallerSha256: 0328BDC2F2F04CDE70EBAEEF67F6DD402DAFA60F335E52BC2C8DDD8B155AC016
  InstallerSwitches:
    Custom: /ALLUSERS
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
