# Created using wingetcreate

PackageIdentifier: Kiwix.WikiMed
PackageVersion: 1.7.4.0
Installers:
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.10240.0
  Architecture: neutral
  InstallerType: msix
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.7.4-WikiMed/KiwixWebAppWikiMed_1.7.4.0_AnyCPU.appxbundle
  InstallerSha256: 70723034D5FDD491EF86B92BEC767D1499302600984FBAD861E25A93D47033CC
  SignatureSha256: 752A9638193CA3B6240F492A4A9619F0E157E952959D8BC879C07BD282C2813B
  PackageFamilyName: Kiwix.WikiMed_qwjmsdmcnwx12
ManifestType: installer
ManifestVersion: 1.0.0
